services:
  # Caddy webserver
  caddy:
    container_name: caddy
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80 # Needed for HTTP->HTTPS redirection
      - 443:443
      - 443:443/udp
    volumes:
      # Caddy routes files (read-only)
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

      # Directory with site data (read-only)
      # php-fpm will perform writes when needed, Caddy does not need write access
      - ./site:/app/public:ro

      # Caddy certificates and other temporary data
      - ./caddy-data:/data

      # Caddy configuration
      - ./caddy-config:/config
    depends_on:
      - php-fpm
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2019/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Custom PHP container
  php-fpm:
    container_name: php-fpm
    user: 'www-data:www-data'
    build:
      context: .
      dockerfile: ./Dockerfile-php
    restart: unless-stopped
    volumes:
      # Directory with site data (with write access)
      - ./site:/app/public
    depends_on:
      database:
        condition: service_healthy

  # MariaDB database
  # No ports are open, only Shopware itself has access
  database:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    cap_add:
      # Allow memory binding
      - SYS_NICE
    environment:
      # Change these if needed
      MARIADB_DATABASE: "shopware"
      MARIADB_ROOT_PASSWORD: "shopware"
    volumes:
      # Database data
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 10s
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  # Scheduled task runner
  shopware_sched_task_runner:
    container_name: shopware_sched_task_runner
    user: 'www-data:www-data'
    build:
      context: .
      dockerfile: ./Dockerfile-php
    command: /usr/local/bin/php /app/public/bin/console scheduled-task:run --memory-limit=512M --no-interaction --no-ansi
    restart: unless-stopped
    volumes:
      # Directory with site data (with write access)
      - ./site:/app/public
    depends_on:
      caddy:
        condition: service_healthy

  # Messenger consumer
  shopware_messenger_runner:
    container_name: shopware_messenger_runner
    user: 'www-data:www-data'
    build:
      context: .
      dockerfile: ./Dockerfile-php
    command: /usr/local/bin/php /app/public/bin/console messenger:consume async low_priority --memory-limit=512M --no-interaction --no-ansi
    restart: unless-stopped
    volumes:
      # Directory with site data (with write access)
      - ./site:/app/public
    depends_on:
      caddy:
        condition: service_healthy