FROM php:8.3-fpm-bullseye

# Update the system
RUN apt update -y
RUN apt upgrade -y

RUN apt install -y build-essential
RUN apt install -y libonig-dev zlib1g-dev libpng-dev libicu-dev libzip-dev
RUN apt install -y cron

# Install extensions
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install gd
RUN docker-php-ext-install intl
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip

# Install OPCache
RUN docker-php-ext-configure opcache --enable-opcache
RUN docker-php-ext-install opcache

# Add extra configuration options
RUN echo 'memory_limit = 1024M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;
RUN echo 'opcache.memory_consumption = 256' >> /usr/local/etc/php/conf.d/docker-php-opcache.ini;
RUN echo 'max_execution_time = 180' >> /usr/local/etc/php/conf.d/docker-php-exec-time.ini;

RUN echo '0 1 * * * /app/public/bin/console messenger:consume async low_priority --time-limit=120 --memory-limit=512M --no-interaction --no-ansi --quiet --no-wait' >> /etc/cron.d/shopware
RUN echo '0 0 * * * /app/public/bin/console scheduled-task:run --time-limit=120 --memory-limit=512M --no-interaction --no-ansi --no-wait' >> /etc/cron.d/shopware
RUN chmod 0644 /etc/cron.d/shopware
RUN crontab /etc/cron.d/shopware

# Run the cron service
CMD cron && php-fpm