FROM php:8.3-fpm-bullseye

# Update the system
RUN apt update -y
RUN apt upgrade -y

RUN apt install -y build-essential
RUN apt install -y libonig-dev zlib1g-dev libpng-dev libicu-dev libzip-dev
RUN apt install -y nano

# Install extensions
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install gd
RUN docker-php-ext-install intl
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install zip
RUN pecl install zstd
RUN docker-php-ext-enable zstd

# Install OPCache
RUN docker-php-ext-configure opcache --enable-opcache
RUN docker-php-ext-install opcache

# Add extra configuration options
RUN echo 'memory_limit = 1024M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;
RUN echo 'opcache.memory_consumption = 256' >> /usr/local/etc/php/conf.d/docker-php-opcache.ini;
RUN echo 'max_execution_time = 180' >> /usr/local/etc/php/conf.d/docker-php-exec-time.ini;
RUN echo 'pm.max_children = 16' >> /usr/local/etc/php-fpm.d/zz-docker.conf;
RUN echo 'pm.max_requests = 16' >> /usr/local/etc/php-fpm.d/zz-docker.conf;

# OPCache tuning
RUN echo 'opcache.enable_file_override=1' >> /usr/local/etc/php/conf.d/docker-php-opcache.ini;
RUN echo 'opcache.interned_strings_buffer=20' >> /usr/local/etc/php/conf.d/docker-php-opcache.ini;
#RUN echo 'opcache.preload = /app/public/var/cache/opcache-preload.php' >> /usr/local/etc/php/conf.d/docker-php-opcache.ini;
#RUN echo 'opcache.preload_user = www-data' >> /usr/local/etc/php/conf.d/docker-php-opcache.ini;

# Performance optimizations
RUN echo 'zend.assertions=-1' >> /usr/local/etc/php/conf.d/docker-php-sw-opts.ini;
RUN echo 'zend.detect_unicode=0' >> /usr/local/etc/php/conf.d/docker-php-sw-opts.ini;
RUN echo 'realpath_cache_ttl=3600' >> /usr/local/etc/php/conf.d/docker-php-sw-opts.ini;

# Copy the entrypoint script
COPY ./entrypoint-php.sh /entrypoint.sh
# Make it executable
RUN chmod +x /entrypoint.sh

STOPSIGNAL SIGTERM

# Run php-fpm
CMD ["/entrypoint.sh"]